update index.html
azmedservices/azmedservices.github.io pull request #6
Opened 2018-09-05 18:45 UTC by techbelle

make searchable and indexable by spiders; add meta data descriptors, change some content to use keywords more effectively.

2018-09-06 13:24 UTC, Frick requested changes
A few changes I'd definitely like to see, but some of the included is just discussion.

2018-09-06 13:24 UTC, Frick commented on index.html
> +<META NAME="ROBOTS" CONTENT="INDEX, FOLLOW">
I'd indent and lowercase the contents of this line to follow suit with what's already here already.

2018-09-06 13:24 UTC, Frick commented on index.html
>    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
I'd remove the empty line above this and move the comment up as it still stands. The `robots` line can come after.

2018-09-06 13:24 UTC, Frick commented on index.html
> +<meta name="description" content="Arizona Medical Services provides state of the art, in office testing for the RPP Respiratory Pathogen Panel reducing costs and complexity for urgent care providers"
Indent

2018-09-06 13:24 UTC, Frick commented on index.html
> +              medical providers. We've built a unique team of highly trained and knowledgeable consultants to
The first sentence no longer makes sense to me. Maybe the below?
```
We understand the complex, evolving landscape that impacts today's medical providers.
```

2018-09-06 13:24 UTC, Frick commented on index.html
> +              and direct recommendations in processes and products, that will streamline your operations and allow your facility
Remove the comma after `products`.

2018-09-06 13:24 UTC, Frick commented on index.html
> +              and make a true comprehensive health and wellness plan. Be part of this revolution in healthcare, proactively anticipate your patient's needs.
```
Be part of this revolution in healthcare, proactively anticipate your patient's needs.
```
just doesn't read well to me. I'd think either of the below might be better.
```
Be part of this revolution in healthcare by proactively anticipating your patient's needs.
```
```
Be part of this revolution in healthcare. Proactively anticipate your patient's needs.
```

2018-09-06 13:24 UTC, Frick commented on index.html
> +            <p>Alongside DNA testing, Arizona Medical Services can help your office deliver fast, convenient testing for specific pathogens and sensitivities - giving
Honestly... I kinda prefer the original statement. Perhaps just prefix the original with `Arizona Medical Service's `?

2018-09-06 13:24 UTC, Frick commented on index.html
> +            <p>User friendly, fast, thorough, secure data for doctors and nurses. Easy integrations. Training for your staff.
I'm not sure I like the old or new text. The old is a little long-winded (and uses `faster` twice), the new is a little harsh and sounds more like it should be a bulleted list.

2018-09-17 01:14 UTC, techbelle reviewed
ready for review again

2018-09-19 02:56 UTC, Frick approved these changes
:man_shrugging:

2018-09-19 03:35 UTC, techbelle commented
@bizarrowill can you please merge this pull request when you get a chance

2018-09-19 06:30 UTC, merged